int controller_cargarJugadoresDesdeTexto(char* path , LinkedList* pArrayListJugador);
int controller_cargarJugadoresDesdeBinario(char* path , LinkedList* pArrayListJugador);
int controller_agregarJugador(LinkedList* pArrayListJugador);
int controller_editarJugador(LinkedList* pArrayListJugador);
int controller_removerJugador(LinkedList* pArrayListJugador);
int controller_listarJugadores(LinkedList* pArrayListJugador);
int controller_ordenarJugadoresNacionalidad(LinkedList* pArrayListJugador);
int controller_guardarJugadoresModoTexto(char* path , LinkedList* pArrayListJugador);
int controller_guardarJugadoresModoBinario(char* path , LinkedList* pArrayListJugador);
int controller_cargarSeleccionesDesdeTexto(char* path , LinkedList* pArrayListSeleccion);
int controller_editarSeleccion(LinkedList* pArrayListSeleccion);
int controller_listarSelecciones(LinkedList* pArrayListSeleccion);
int controller_ordenarSelecciones(LinkedList* pArrayListSeleccion);
int controller_guardarSeleccionesModoTexto(char* path , LinkedList* pArrayListSeleccion);
int controller_listaDeListados(LinkedList* pArrayListSeleccion, LinkedList* pArrayListJugador);
int controller_idSubSiguiente (LinkedList* pArrayListJugador);
int controller_buscarPorIdJugador(LinkedList* pArrayListJugador,int idABuscar);
int controller_buscarPorIdSeleccion(LinkedList* pArrayListSeleccion,int idABuscar);
int controller_convocarJugador(LinkedList* pArrayListJugador, LinkedList* pArrayListSeleccion);
int controller_listarJugadoresConvocados(LinkedList* pArrayListJugador);
int controller_quitarJugadorConvocado(LinkedList* pArrayListJugador, LinkedList* pArrayListSeleccion);
int controller_ordenarSeleccionPorConfederacion(void *seleccion1, void *seleccion2);
int controller_OrdenarJugadorPorEdad(void *jugador1, void *jugador2);
int controller_ordenarPorJugadorNacionalidad(void *nombre1, void *nombre2);
int controller_ordenarJugadorPorNombre(void *nombre1, void *nombre2);
int controller_ordenarJugadoresNombre(LinkedList* pArrayListJugador);
int controller_ordenarJugadoresEdad(LinkedList* pArrayListJugador);
int controller_filtarConvocados(LinkedList* pArrayListJugador, LinkedList* jugConvocados );
